# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=100)),
                ('photo_pet', models.FileField(upload_to='photos/')),
                ('votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo_pet', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='mascota.Usuario')),
            ],
        ),
    ]
